---
version: "3"

volumes:
  postgres:

services:
  postgres:
    command: postgres -c max_connections=200 -c listen_addresses='*'
    environment:
      POSTGRES_USER: nomadia
      POSTGRES_DATABASE: nomadia
      POSTGRES_PASSWORD: nomadia
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "35432:5432"